<a href="https://colab.research.google.com/github/raiyan-09/Coding-task/blob/main/Coding_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# importing libraries
import matplotlib.pyplot as plt
import numpy as np
import random

# feed-forward network
# taking random input of x matrix
input_data = np.random.randint(1, 30, size=(1, 2)) 
input_data = np.array(input_data)

# taking random input of Weight matrix of hidden layer
weight_data = np.random.uniform(1, 30, size=(4, 2))


weights= {'node_0': np.array(weight_data[0]),
          'node_1': np.array(weight_data[1]),
          'node_2': np.array(weight_data[2]),
          'node_3': np.array(weight_data[3]),
          }

# taking random input of output side Weight matrix         
output_weights = np.random.uniform(1, 30, size=(1, 4))
b1             = np.random.uniform(700, 1000, size=(1, 4)) 
# calculating z values of each node in hidden layer
# node_0_value = ((input_data * weights['node_0']).sum()) + b1[0][0]
# node_1_value = (((input_data * weights['node_1']).sum()) + b1[0][1]
# node_2_value = ((input_data * weights['node_2']).sum()) + b1[0][2]
# node_3_value = ((input_data * weights['node_3']).sum()) + b1[0][3]
node_0_value = (input_data * weights['node_0']).sum() 
node_0_value = node_0_value + b1[0][0]
node_1_value = (input_data * weights['node_1']).sum()
node_1_value = node_1_value + b1[0][1]
node_2_value = (input_data * weights['node_2']).sum() 
node_2_value = node_2_value + b1[0][2]
node_3_value = (input_data * weights['node_3']).sum()
node_3_value = node_3_value + b1[0][3]
# np.maximum(0, Z)
# calculating activation values in hidden layer 
ReLu_node_0_value = np.maximum(0, node_0_value)
ReLu_node_1_value = np.maximum(0, node_1_value)
ReLu_node_2_value = np.maximum(0, node_2_value)
ReLu_node_3_value = np.maximum(0, node_3_value)

hidden_layer_values = np.array([ReLu_node_0_value,ReLu_node_1_value,ReLu_node_2_value,ReLu_node_3_value])
# sigmoid_hidden_layer_values = 1/(1+np.exp(-hidden_layer_values))

output =  ( hidden_layer_values * output_weights ).sum()
b2 = np.random.uniform(700,1000)
output = output+ b2
output
sigmoid_output= 1/(1+np.exp(-output))
sigmoid_output

1.0

In [16]:
# Backpropagation

Y   = np.random.randint(0,1)
X  = input_data
A1 = hidden_layer_values
A2 = sigmoid_output
W2 = output_weights

print(Y)
print(X)
print(A1)
print(A2)
print(W2)
print(A2)

0
[[22 20]]
[1444.23731828 1661.22459496 1309.45946023 1663.77123186]
1.0
[[29.33388006  1.42931353  7.86400929 24.04648662]]
1.0


In [17]:
dZ2 = A2 - Y
print(A2)
print(Y)
print(dZ2)


1.0
0
1.0


In [18]:
m   =  np.random.randint(100,1000)
print(m)

515


In [19]:
dW2 = (1 / m) * np.dot(dZ2, A1.T)
print(dZ2)
print(A1.T)
print(dW2)

1.0
[1444.23731828 1661.22459496 1309.45946023 1663.77123186]
[2.80434431 3.22567883 2.54263973 3.23062375]


In [20]:
dZ2 = np.array([[dZ2]])
# dZ2   = np.random.randint(1, 30, size=(1, 1))
print(dZ2)
db2 = (1 / m) * np.sum(dZ2, axis = 1, keepdims = True)
print(db2)



[[1.]]
[[0.00194175]]


In [21]:
print(W2)
print(W2.T)

[[29.33388006  1.42931353  7.86400929 24.04648662]]
[[29.33388006]
 [ 1.42931353]
 [ 7.86400929]
 [24.04648662]]


In [22]:
print(dZ2)


[[1.]]


In [23]:
print(np.dot(W2.T, dZ2))

[[29.33388006]
 [ 1.42931353]
 [ 7.86400929]
 [24.04648662]]


In [24]:
# dZ1 = np.multiply(np.dot(W2.T, dZ2), 1 - np.power(A1, 2))
dZ1 = np.multiply(np.dot(W2.T, dZ2), A1-np.power(A1, 2))
# print(np.dot(W2.T, dZ2))
# print(A1)
# print(np.power(A1, 2))
print(dZ1)

[[-61142870.6239375  -80903015.1778552  -50259925.56582295
  -81151326.77846046]
 [ -2979228.51594881  -3942055.17968832  -2448949.51655317
   -3954154.33358501]
 [-16391561.6194523  -21688984.2585853  -13473993.91775922
  -21755553.17922333]
 [-50121948.31289808 -66320352.70379541 -41200639.84097669
  -66523906.46376816]]


In [25]:
db1 = (1 / m) * np.sum(dZ1, axis = 1, keepdims = True)
print(db1)

[[-530984.73426423]
 [ -25872.59717626]
 [-142349.69509713]
 [-435275.43169211]]


In [26]:
# dW1 = (1 / m) * np.dot(dZ1, X.T) 
#error is showing as dz1 is (4*4) size matrix and X.T is (2*1 size matrix)

In [27]:
learning_rate = 0.01
# Updating the parameters according to algorithm
# W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1
W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2    