<a href="https://colab.research.google.com/github/raiyan-09/Coding-task/blob/main/Coding_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [518]:
# importing libraries
import matplotlib.pyplot as plt
import numpy as np
import random

# taking random input of x matrix
input_data = np.random.randint(1, 30, size=(1, 2)) 
input_data = np.array(input_data)

# taking random input of Weight matrix of hidden layer
weight_data = np.random.uniform(1, 30, size=(4, 2))


weights= {'node_0': np.array(weight_data[0]),
          'node_1': np.array(weight_data[1]),
          'node_2': np.array(weight_data[2]),
          'node_3': np.array(weight_data[3]),
          }

# taking random input of output side Weight matrix         
output_weights = np.random.uniform(1, 30, size=(1, 4))
b1             = np.random.uniform(700, 1000, size=(1, 4)) 
# calculating z values of each node in hidden layer
# node_0_value = ((input_data * weights['node_0']).sum()) + b1[0][0]
# node_1_value = (((input_data * weights['node_1']).sum()) + b1[0][1]
# node_2_value = ((input_data * weights['node_2']).sum()) + b1[0][2]
# node_3_value = ((input_data * weights['node_3']).sum()) + b1[0][3]
node_0_value = (input_data * weights['node_0']).sum() 
node_0_value = node_0_value + b1[0][0]
node_1_value = (input_data * weights['node_1']).sum()
node_1_value = node_1_value + b1[0][1]
node_2_value = (input_data * weights['node_2']).sum() 
node_2_value = node_2_value + b1[0][2]
node_3_value = (input_data * weights['node_3']).sum()
node_3_value = node_3_value + b1[0][3]
# np.maximum(0, Z)
# calculating activation values in hidden layer 
ReLu_node_0_value = np.maximum(0, node_0_value)
ReLu_node_1_value = np.maximum(0, node_1_value)
ReLu_node_2_value = np.maximum(0, node_2_value)
ReLu_node_3_value = np.maximum(0, node_3_value)

hidden_layer_values = np.array([ReLu_node_0_value,ReLu_node_1_value,ReLu_node_2_value,ReLu_node_3_value])
# sigmoid_hidden_layer_values = 1/(1+np.exp(-hidden_layer_values))

output =  ( hidden_layer_values * output_weights ).sum()
b2 = np.random.uniform(700,1000)
output = output+ b2
output
sigmoid_output= 1/(1+np.exp(-output))
sigmoid_output

1.0

In [519]:
# #if Y = 0 is real output
# Y   = np.random.randint(0,1)

# #def back_propagate(W1, b1, W2, b2, cache):
   
# # Retrieve also A1 and A2 from dictionary "cache"
# X  = input_data
# A1 = hidden_layer_values
# A2 = sigmoid_output
# W2 = output_weights
  
# # Backward propagation: calculate dW1, db1, dW2, db2. 
# dZ2 = A2 - Y
# # m is total number of samples 
# m   =  np.random.randint(100,1000)
# dW2 = (1 / m) * np.dot(dZ2, A1.T)
# # db2 = (1 / m) * np.sum(dZ2, axis = 1, keepdims = True)



# dZ1 = np.multiply(np.dot(W2.T, dZ2), 1 - np.power(A1, 2))

# dZ1
# X

# dW1 = (1 / m) * np.dot(dZ1, X.T)
# db1 = (1 / m) * np.sum(dZ1, axis = 1, keepdims = True)
      
# # Updating the parameters according to algorithm
# W1 = W1 - learning_rate * dW1
# b1 = b1 - learning_rate * db1
# W2 = W2 - learning_rate * dW2
# b2 = b2 - learning_rate * db2
  
# # return W1, W2, b1, b2

In [520]:
Y   = np.random.randint(0,1)

X  = input_data
A1 = hidden_layer_values
A2 = sigmoid_output
W2 = output_weights

print(Y)
print(X)
print(A1)
print(A2)
print(W2)
print(A2)

0
[[12 27]]
[1578.2994632  1320.9461357  1472.11726852 1851.17021702]
1.0
[[16.10776564 12.65926988 20.40664736 20.47266542]]
1.0


In [521]:
dZ2 = A2 - Y
print(A2)
print(Y)
print(dZ2)


1.0
0
1.0


In [522]:
m   =  np.random.randint(100,1000)
print(m)

509


In [523]:
dW2 = (1 / m) * np.dot(dZ2, A1.T)
print(dZ2)
print(A1.T)
print(dW2)

1.0
[1578.2994632  1320.9461357  1472.11726852 1851.17021702]
[3.1007848  2.59517905 2.89217538 3.63687665]


In [524]:
dZ2 = np.array([[dZ2]])
# dZ2   = np.random.randint(1, 30, size=(1, 1))
print(dZ2)
db2 = (1 / m) * np.sum(dZ2, axis = 1, keepdims = True)
print(db2)



[[1.]]
[[0.00196464]]


In [525]:
print(W2)
print(W2.T)

[[16.10776564 12.65926988 20.40664736 20.47266542]]
[[16.10776564]
 [12.65926988]
 [20.40664736]
 [20.47266542]]


In [526]:
print(dZ2)


[[1.]]


In [527]:
print(np.dot(W2.T, dZ2))

[[16.10776564]
 [12.65926988]
 [20.40664736]
 [20.47266542]]


In [528]:
# dZ1 = np.multiply(np.dot(W2.T, dZ2), 1 - np.power(A1, 2))
dZ1 = np.multiply(np.dot(W2.T, dZ2), A1-np.power(A1, 2))
# print(np.dot(W2.T, dZ2))
# print(A1)
# print(np.power(A1, 2))
print(dZ1)

[[-40099491.61483076 -28085141.73440098 -34883897.59468361
  -55168775.20810934]
 [-31514630.73651599 -22072421.25271758 -27415638.13094073
  -43357746.16719569]
 [-50801346.54746459 -35580576.22746214 -44193801.4490528
  -69892359.10686156]
 [-50965695.26522105 -35695683.84718942 -44336773.93097608
  -70118469.64094858]]


In [529]:
db1 = (1 / m) * np.sum(dZ1, axis = 1, keepdims = True)
print(db1)

[[-310878.79401184]
 [-244323.05753904]
 [-393846.92206452]
 [-395121.06617748]]


In [530]:
# dW1 = (1 / m) * np.dot(dZ1, X.T)


In [531]:
learning_rate = 0.01
# Updating the parameters according to algorithm
# W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1
W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2    